---
- name: playbook
  hosts: localhost
  gather_facts: false
  vars_files:
   - var.yml
  tasks:
   - name: test ansible
     shell: touch test2.sh
   - name: Instablling packages
     apt:
      name: "{{ item }}"
      state: present
     with_items:
      - "{{ packages }}"
   - name: Check to see if you can connect to a page & it return 200
     uri: 
      url: http://www.ibm.com
     register: test
   - name: Print output
     debug:
      msg: "{{ test.status }}"  


